### ISSUE TITLE
How do I import BuildTimeComponent?

### ISSUE THREAD

**Issue by samselikoff** [cibernox/ember-ast-helpers#19]
I tried copying [this line](https://github.com/martndemus/ember-font-awesome/blob/118c8e3dac3c2bbdd1edb1acee1ab4d07fd4766c/lib/build-time-components/fa-icon.js#L4) from Ember Font Awesome

```js
const { default: BuildTimeComponent, interpolateProperties } = require('ember-ast-helpers/build-time-component');
```

but I got an error

> Cannot find module 'ember-ast-helpers/build-time-component'

and my node-fu is extremely weak.

**Comment by samselikoff** [comment]
I changed it to

```
const { default: BuildTimeComponent } = require('ember-ast-helpers/dist/lib/build-time-component');
```

and now I'm getting

> Cannot find module '@ glimmer/syntax'

I'm on the latest commit.

**Comment by cibernox** [comment]
I would expect it to work. Can you clone ember-font-awesome and see if you are able to build it?

**Comment by samselikoff** [comment]
It uses 0.3.5, should I downgrade to there? I noticed 0.4.x was latest on npm

**Comment by cibernox** [comment]
I was in the process of updating ember-font-awesome to 0.4.0 but then I had to travel. I was expecting breaking changes but not the module system actually. I'd suggest you use 0.3.X, changes will not be that dramatic.

**Comment by samselikoff** [comment]
Sweet, 0.3.x works.

PR for README here https://github.com/cibernox/ember-ast-helpers/pull/20
